### ISSUE TITLE
file upload from webpage save as random file name

### ISSUE THREAD

**Issue by 54shady** [crycode-de/http-server-upload#17]
i got a upload.html file like below

      

> <!DOCTYPE html>
>       <html lang="en">
>       <head>
>         <meta charset="utf-8"/>
>         <title>upload</title>
>       </head>
>       <body>
>           <form action="http://localhost:8081/upload" method="post" enctype="multipart/form-data">
>         <p><input type="file" name="file1">
>         <p><button type="submit">Submit</button>
>       </form>
>       </body>
>       </html>

when i upload file from web page, the file will be save  as some kind of random name?

i check the code below, the file is undefine, which retuan in line if(!file) return

 let count = 0;
        files.uploads.forEach((file) => {
          if (!file) return; 
          const newPath = path.join(uploadDir, fields.path, file.originalFilename);
          fs.renameSync(file.filepath, newPath);
          console.log(new Date().toUTCString(), '- File uploaded', newPath);
          count++;
        });

any idea to fix this issue?

**Comment by crycode-de** [comment]
Why did you change the name of the file input element in the HTML?
This input is expected to be named `uploads`:

https://github.com/crycode-de/http-server-upload/blob/8af34cc1176c21cd7431b0ffa8ae103452d6e1ff/http-server-upload.js#L274

If you really need to change this for some reason, you have to change all occurrences of `files.uploads` with `files.yourNameHere` in the code.

Also seams like you are using an outdated version of `http-server-upload`.
Consider updating to the latest release (currently v2.2.2).
