### ISSUE TITLE
No authentication option

### ISSUE THREAD

**Issue by panicstack** [crycode-de/http-server-upload#2]
Thank you creating such a straight forward haslefree program.

**Issue:**
````
There is no option to enable authentication.
WebDAV server without authentication is very risky. 
Please add an option to enable authentication.
````

**Comment by crycode-de** [comment]
Hi, you may use the `TOKEN` environment variable to set a token, which is then required for each upload request.
Example: `TOKEN=4074c9f6-6f4a-4468-b4cc-28503f4aeeb7 http-server-upload`

To keep it as simple as possible, no other authentication methods will be supported by this tool.
If you need one, consider running a reverse proxy (e.g. nginx) in front of _http-server-upload_.
