### ISSUE TITLE
[RFE] Provide a container image

### ISSUE THREAD

**Issue by e-minguez** [crycode-de/http-server-upload#32]
It would be nice to have http-server-upload already available as a container somewhere.

**Comment by crycode-de** [comment]
Can you explain this in a little more detail? What kind of container and what purpose?

**Comment by e-minguez** [comment]
Sure! I was thinking about having an already available docker container so it can be used as `docker run foobar/http-server-upload:latest` (with the proper volume mounts, permissions, etc.) The idea is to be able to use it in docker hosts (or with docker compose as well) but also maybe as a kubernetes pod.

**Comment by crycode-de** [comment]
Thank you! I'll have a look at this as soon as possible.
Should be no big deal. 😉

**Comment by crycode-de** [comment]
A docker image is now available at the docker hub: https://hub.docker.com/r/crycode/http-server-upload

Also the repo includes a Dockerfile and some information in the readme.

Thanks for requesting this and also thanks to @pladen for providing a first docker example!
