### ISSUE TITLE
port configuration

### ISSUE THREAD

**Issue by joebnb** [crycode-de/http-server-upload#4]
pls add auto detect using port and start with other port and add custom port（for firewall）

**Comment by crycode-de** [comment]
You may set a custom port using the `PORT` environment variable.
Example: `PORT=3333 http-server-upload`

**Comment by mindtricksdev** [comment]
specifying env variables from comand line doesn't work easily for Windows..

**Comment by crycode-de** [comment]
On Windows cmd/batch just use:
```batch
set PORT=3333
http-server-upload
```

**Comment by joebnb** [comment]
not a good idea, i think it should be set by process.argv,the word of port easy infect other applications

**Comment by mindtricksdev** [comment]
why not adding port as the next argument? check my PR

**Comment by crycode-de** [comment]
Just released [v2.1.0](https://github.com/crycode-de/http-server-upload/releases/tag/v2.1.0) with support for command line arguments for all options and automatic port increase if the desired port is already in use.
